from fastapi import FastAPI, Depends
from pydantic import BaseModel
from langchain_huggingface import HuggingFacePipeline
from langchain.prompts import PromptTemplate
from typing import Optional
from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM
from sqlalchemy.orm import Session

# DB Imports
from config.database import (
    get_db,
    test_connection,
    get_schema_context_for_llm,
    execute_sql_query,
)

app = FastAPI(title="NL-2-SQL Database Assistant")

# Pydantic model for user queries
class DatabaseQuery(BaseModel):
    question: str
    model_id: Optional[str] = "MPX0222forHF/SQL-R1-7B"

@app.get("/")
def root():
    return {"message": "NL-2-SQL Database Assistant Ready! Visit /docs for Swagger UI."}

@app.get("/db-connect/")
def db_connect():
    """Test database connection and return status."""
    return test_connection()

@app.post("/ask-database/")
def ask_database(query: DatabaseQuery, db: Session = Depends(get_db)):
    """
    Ask a question about the database and get SQL query generated by LLM.
    """
    try:
        # Get database schema for context
        schema_context = get_schema_context_for_llm()
        
        # Load the LLM model
        print(f"Loading model: {query.model_id}")
        tokenizer = AutoTokenizer.from_pretrained(query.model_id)
        model = AutoModelForCausalLM.from_pretrained(
            query.model_id,
            torch_dtype="auto",
            device_map="auto",
            trust_remote_code=True
        )
        
        # Create pipeline
        pipe = pipeline(
            "text-generation",
            model=model,
            tokenizer=tokenizer,
            max_length=512,
            do_sample=True,
            temperature=0.1,
            top_p=0.9,
            pad_token_id=tokenizer.eos_token_id,
            return_full_text=False
        )
        
        llm = HuggingFacePipeline(pipeline=pipe)
        
        # Create prompt for SQL generation
        sql_prompt = PromptTemplate(
            input_variables=["question", "schema"],
            template="""Database Schema:
                    {schema}

                    Question: {question}

                    Generate a SQL query to answer this question. Use only the tables and columns shown in the schema above.

                    SQL Query:""",)
        
        # Generate SQL query
        sql_chain = sql_prompt | llm
        sql_result = sql_chain.invoke({
            "question": query.question,
            "schema": schema_context
        })
        
        # Extract and clean the SQL query
        generated_sql = sql_result.strip()
        if generated_sql.endswith(';'):
            generated_sql = generated_sql[:-1]
        
        # Execute the SQL query
        execution_result = execute_sql_query(generated_sql)
        
        if execution_result["status"] == "error":
            return {
                "question": query.question,
                "generated_sql": generated_sql,
                "answer": f"Error executing query: {execution_result['message']}",
                "success": False,
                "error": execution_result["message"]
            }
        
        # Return results
        return {
            "question": query.question,
            "generated_sql": generated_sql,
            "answer": execution_result.get("data", []),
            "row_count": execution_result.get("row_count", 0),
            "success": True
        }
        
    except Exception as e:
        return {
            "question": query.question,
            "error": f"Error: {str(e)}",
            "success": False
        }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)